// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfgaxqthpuooiarxvokn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmZ2F4cXRocHVvb2lhcnh2b2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MTAxNDksImV4cCI6MjA1NDI4NjE0OX0.84-IkIqtzjs9DlHpMRsaSi_WAYlZ3qZMHCOQFokB9_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);